CodeJaws/Jawstify

next.config.js, package-lock.json, package.json
=> [#10] styled-components 패키지 설치

pages/[boardid]/edit.tsx, pages/[boardid]/index.tsx, pages/boards/index.tsx, pages/dashboard/[dashboardid].tsx, pages/dashboard/index.tsx, pages/index.tsx, pages/login/index.tsx, pages/myboard/index.tsx, pages/mydashboard/index.tsx, pages/notfound/index.tsx, pages/signup/index.tsx
아래는 구현한 페이지 중 일부만 첨부하였습니다. 
- 
-
- 페이지 기본 세팅입니다.
-
=> [#14] Feat: 페이지 구조 설정

styles/fontStyle.tsx
아래와 같이 사용하시면 됩니다.
-
-
- 주의할 점 !! font size px값으로 입력하기! 알아서 rem으로 변환되도록 적용시켰습니다.
-
=> [#18] fontStyle 구현

components/common/Button/AddButton.tsx, components/common/Button/Button.tsx, components/common/Button/ColumnAddButton.tsx, components/common/Button/DashBoardAddButton.tsx, components/common/Button/DashBoardButton.tsx, components/common/Button/DeleteButton.tsx, components/common/Button/TwinButton.tsx, tsconfig.json, types/button.ts
closed #42
- 로그인 버튼은 소은님 코드에서 변경, 페이지네이션 버튼은 종민님 코드에서 변경될 예정
=> [#42] 버튼들에 onClick 기본 설정 추가

components/Input/ModalInputContainer/BasicInput.tsx
=> [#47] BasicInput 주석 삭제

hooks/useDeviceType.ts, pages/_document.tsx
=> [#53] useDeviceType 함수 수정

components/Dashboard/DashboardNavbar.tsx
=> [#61] Fix: 대시보드 헤더 위치 오류 및 CSS 수정

components/Sidebar/DashboardGroup.tsx, components/Sidebar/Sidebar.tsx
=> [#63] Fix: Sidebar CSS 오류 수정

components/ModalDropDown/DropDown.tsx, components/ModalDropDown/DropDownMenu.tsx, components/ModalDropDown/ModalDropDown.tsx, constants/Chip.ts, types/dropdown.ts
- 코멘트로 남기겠습니다
- 코드가 엄청 더럽습니다..
```
import ModalDropDown from '@/components/ModalDropDown/ModalDropDown';
/** Test용 Page입니다. */
function Test() {
return (
<div>
<ModalDropDown type="manager" />
</div>
);
}
export default Test;
```
=> [#51] Modal Input Dropdwon 컴포넌트

apis/api.ts, apis/axios.ts, next.config.js, types/api.ts, utils/localStorage.ts
- 에러 처리는 interceptor를 활용하였습니다.
- 활용 방법만 숙지하고 넘어가도 좋을 것 같습니다.
- 테스트 방법
```tsx
import api from '@/apis/api';
import { useEffect } from 'react';
/** Test용 Page입니다. */
function Test() {
const email = 'test1@codeit.com';
const emailError = 'test1codeit.com';
const password = 'test12345';
// Console을 확인해주세요!!!
const testFunc = async () => {
const testMsg = await api.auth.login({ email, password });
// ERROR Version
// const testMsg = await api.auth.login({ email: emailError, password });
console.log(testMsg);
};
useEffect(() => {
testFunc();
}, []);
return <></>;
}
export default Test;
```
=> [#52] API 작성

components/Modal/ModalContent/Basic.tsx, components/common/Button/TwinButton.tsx
=> [#90] BasicModal 버튼 비활성화 기능 구현

components/Modal/ModalContent/Basic.tsx, components/Modal/ModalContent/Create&EditToDo.tsx, components/Modal/ModalContent/CreateDashboard.tsx, components/Modal/ModalContent/ManageColumn.tsx, constants/InitialModalValues.ts
=> [#102] modal value 기본값 상수화

components/Input/FormInput.tsx
=> [#95] 비밀번호 숨기기 버튼 버그

components/Modal/ModalContent/Basic.tsx, components/Modal/ModalContent/Create&EditToDo.tsx, components/Modal/ModalContent/CreateDashboard.tsx, components/Modal/ModalContent/ManageColumn.tsx, constants/InitialModalValues.ts
- 아무것도없어요 그냥 작은 수정입니다 빠른 어푸 부탁드려요
=> [#102] modal values 상수 이름 대문자로 수정

pages/[dashboardid]/edit.tsx
=> [#129] 대시보드 수정페이지 id 접근 오류 해결

hooks/useRedirectByDashboardId.ts, hooks/useRedriectByLogin.ts, pages/[dashboardid]/edit.tsx, pages/[dashboardid]/index.tsx, pages/boards/index.tsx, pages/dashboard/[dashboardid].tsx, pages/dashboard/index.tsx, pages/index.tsx, pages/login/index.tsx, pages/myboard/index.tsx, pages/mydashboard/index.tsx, pages/mypage/index.tsx, pages/signup/index.tsx
- 로그인 상태일 때 인덱스, 로그인, 회원가입 페이지에 들어갈 수 없게 구현했습니다.(mydashboard로 redirect)
- 비로그인 상태에서 로그인해야 이용할 수 있는 서비스 접근 시 index page로 redirect
- 대시보드 멤버가 아닐 시 대시보드 아이디를 uri에서 사용하는 페이지에 들어갈 수 없게 구현했습니다.(mydashboard로 redirect)
=> [#123] 리다이렉션 구현

components/DashboardNavbar/DashboardNavbar.tsx, components/DashboardNavbar/Profile.tsx, pages/dashboard/[dashboardid].tsx
- 회의 때 상의했던 부분들 코드에 반영하여 수정했습니다.
=> [#128] 대시보드 Navbar 오류 수정

hooks/useRedirectByLogin.ts, pages/[dashboardid]/edit.tsx, pages/[dashboardid]/index.tsx, pages/boards/index.tsx, pages/dashboard/[dashboardid].tsx, pages/dashboard/index.tsx, pages/index.tsx, pages/login/index.tsx, pages/myboard/index.tsx, pages/mydashboard/index.tsx, pages/mypage/index.tsx, pages/signup/index.tsx
=> [#134] useRedriectByLogin 함수 이름 변경

components/Columns/Column.tsx, components/DashboardNavbar/DashboardNavbar.tsx, components/Edit/DashboardEdit.tsx, components/Landing/Nav.tsx, components/Landing/Point.tsx, components/Table/InviteDetailsTable.tsx, components/Table/MembersTable.tsx, pages/[dashboardid]/edit.tsx, types/api.ts
- API의 타입 수정으로 인해 api type들을 수정했습니다.
=> [#140] Fix: string type을 받는 id 값들 number type으로 수정

components/Chip/ColorChip.tsx, components/DashboardNavbar/Profile.tsx, components/Edit/DashboardEdit.tsx, components/Edit/MobileColorChip.tsx, components/Sidebar/Dashboard.tsx, components/Sidebar/Sidebar.tsx, components/Table/InviteDetailsTable.tsx, components/Table/MembersTable.tsx, constants/InitialModalValues.ts, pages/[dashboardid]/edit.tsx
=> [#136] 수정페이지 오류 해결

components/DashboardNavbar/DashboardDropdown.tsx, pages/myboard/index.tsx
=> [#143] 내 대시보드 가기 경로 수정

constants/Metadata.ts, pages/_document.tsx
=> [#151] MetaData 설정

pages/boards/index.tsx, pages/dashboard/index.tsx, pages/test/index.tsx
=> [#158] 사용하지 않는 페이지 컴포넌트들 삭제

components/Input/ModalInputContainer/BasicInput.tsx, components/Input/ModalInputContainer/TagInput.tsx, components/ModalDropDown/DropDown.tsx, components/ModalDropDown/DropDownMenu.tsx, components/Table/InviteDashBoard.tsx
- 할일 생성 모달에서 인풋 글자 색상 수정했습니다
-
-
-
=> [#126] 인풋 글자 색상 수정

components/Modal/Modal.tsx, components/Modal/ModalContent/NoTitle.tsx, components/Sidebar/Dashboard.tsx, components/Sidebar/Sidebar.tsx, hooks/UseSidebarDashboard.ts, hooks/useMyDashboard.ts, pages/[dashboardid]/edit.tsx, pages/dashboard/[dashboardid].tsx, pages/mydashboard/index.tsx, pages/mypage/index.tsx
- 전 페이지에서 사이드바에 있는 대시보드 생성하기 테스트
-
-
=> [#164] 사이드바 렌더링 관련 오류 해결 및 안쓰이는 state, props 제거

components/ModalCard/Menu.tsx, hooks/useComment.ts
=> [#166] 카드 삭제시, 뒤로가는 버그 수정

components/Columns/Column.tsx
=> [#168] 댓글 달리면 카드 사라지는 버그 수정

components/Columns/Column.tsx
=> [#170] 대시보드 카드 생성 관련 함수 수정

package-lock.json, package.json
=> [#190] Tanstack query 라이브러리 설치

pages/_app.tsx
- 공식문서를 참고하였습니다.
- Hydration 문제는 API를 server쪽에서 불러오는 코드가 없기 때문에 혹시나 있을 오류를 방지하고자 뺐습니다.
- ReactQueryDevtools를 설치했습니다.
=> [#192] Tanstack Query 초기 설정

lib/gtag.js, pages/_app.tsx, tsconfig.json
=> [#195] Google Analytics 연결

apis/queries/cards.ts, apis/queries/columns.ts, components/ModalCard/Comment.tsx, components/Table/InviteDetailsTable.tsx, components/Table/MembersTable.tsx, hooks/Common/usePagination.ts, hooks/Dashboard/useDashboard.ts, hooks/DashboardNavbar/useDashboardNavbar.ts, hooks/Edit/useDashboardEdit.ts, hooks/Edit/useInviteDetailsTable.ts, hooks/ModalCard/useModalCard.ts, hooks/useComment.ts, pages/[dashboardid]/edit.tsx
- 폴더 이름 변경하면 관련된 파일들 import문 한번씩 확인해봅시다~
- 댓글 컴포넌트는 react-query로 해보다가 다른거는 이상 없는데 무한 스크롤쪽에서 오류가 발생해서
- 기존 코드로 복구 했습니다 😓
=> [#205] 폴더 이름 변경으로 인한 오류 / 댓글 수정하기 오류

apis/queries/auth.ts, apis/queries/cards.ts, apis/queries/columns.ts, apis/queries/dashboard.ts, apis/queries/users.ts, components/GoogleLogin/GoogleLogin.tsx, hooks/Auth/useAuth.ts, hooks/Common/usePagination.ts, hooks/DropDown/useDropDown.ts, hooks/DropDown/useDropDownMenu.ts, hooks/ModalCard/useModalCard.ts, pages/login/index.tsx, pages/signup/index.tsx
- 아 대시보드 페이지도 하려고했는데 포기합니다 제가 졌습니다
- 코드가 서로 연결되어있는게 많아서 복잡해서 못해먹겠어요 계속 하다간 성질이 더러워질것같아서 적용 성공한거만 올립니다...^^
- !!!!!!!!!!!
=> [#197] Login, Signup React-Query 적용

components/Table/InviteDetailsTable.tsx, components/Table/MembersTable.tsx, pages/[dashboardid]/edit.tsx, pages/_app.tsx
X
- 계속 보이는 오류 👻
https://github.com/CodeJaws/Jawstify/assets/49686619/8142ad66-d16b-4880-8506-431a2880bf04
=> [#210] 관리 페이지 css 수정

components/MyDashboard/MyDashBoardButtonBox.tsx, components/common/Button/LoginButton.tsx, components/common/Button/PaginationButton.tsx
- 이전의 페이지네이션 버튼 이미지가 잘못 불러와 나타나는 오류를 수정했습니다.
=> [#214] 페이지네이션 버튼 이미지 오류 수정

apis/queries/auth.ts, apis/queries/cards.ts, apis/queries/columns.ts, apis/queries/dashboard.ts, apis/queries/users.ts, components/GoogleLogin/GoogleLogin.tsx, components/Modal/ModalContent/CreateDashboard.tsx, hooks/Auth/useAuth.ts, hooks/Auth/useRedirectByLogin.ts, hooks/Dashboard/useDashboard.ts, hooks/Dashboard/useInviteDashBoard.ts, hooks/Dashboard/useRedirectByDashboardId.ts, hooks/DashboardNavbar/useDashboardNavbar.ts, hooks/DashboardNavbar/useProfile.ts, hooks/DropDown/useDropDown.ts, hooks/DropDown/useDropDownMenu.ts, hooks/Edit/useDashboardEdit.ts, hooks/Edit/useInviteDetailsTable.ts, hooks/ModalCard/useModalCard.ts, hooks/Modals/useCreateToDo.ts, hooks/Modals/useEditTodo.ts, hooks/useComment.ts, hooks/useDashboard.ts, pages/signup/index.tsx, types/apiType.ts
X
- alert로 되어 있던거, toast로 변경하였습니다.
- 상대경로로 되어 있던 것들 절대경로로 변경하였습니다.
=> [#216] alert -> toast 전환

apis/axios.ts, apis/queries/auth.ts, apis/queries/cards.ts, apis/queries/columns.ts, apis/queries/dashboard.ts, apis/queries/members.ts, apis/queries/users.ts, components/DashboardNavbar/DashboardDropdown.tsx, components/GoogleLogin/GoogleLogin.tsx, constants/QueryKey.ts, hooks/Auth/useAuth.ts, hooks/Auth/useRedirectByLogin.ts, hooks/Modals/useCreateToDo.ts, hooks/Modals/useEditTodo.ts, hooks/useDashboard.ts, package-lock.json, package.json, pages/_app.tsx
- 리액트 쿼리 키를 효율적으로 유지보수하기 위해 상수화하였습니다.
=> [#218] accessToken 저장 방식 localStorage -> cookie로 변경
